	<footer id="fh5co-footer" role="contentinfo">
		<div class="container">
			<div class="row row-pb-md">
				<div class="col-md-3 fh5co-widget">
					<h4>ABOUT ITOVE</h4>
					<p>ITOVE 为中小企业定制完善的 IT 解决方案。</p>
				</div>
				<div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1">
					<h4>ITOVE</h4>
					<ul class="fh5co-footer-links">
						<li><a href="product">product</a></li>
						<li><a href="faq">faq</a></li>
						<li><a href="http://blog.itove.com">blog</a></li>
						<li><a href="contact">contact</a></li>
						<li><a href="api">api</a></li>
					</ul>
				</div>

				<div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1">
					<h4>TODO</h4>
					<ul class="fh5co-footer-links">
						<li><a href="#">recruit</a></li>
						<li><a href="#">build</a></li>
						<li><a href="#">marketing</a></li>
						<li><a href="#">ssl</a></li>
						<li><a href="#">api</a></li>
					</ul>
				</div>

				<div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1">
					<h4>PROJECT</h4>
					<ul class="fh5co-footer-links">
						<li><a href="#">vpn</a></li>
						<li><a href="#">bash</a></li>
						<li><a href="#">wechat</a></li>
						<li><a href="#">actod</a></li>
					</ul>
				</div>

				<div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1">
					<h4>TEAM</h4>
					<ul class="fh5co-footer-links">
						<li><a href="#">richard</a></li>
						<li><a href="#">dennis</a></li>
						<li><a href="https://dotcra.com">dotcra</a></li>
					</ul>
				</div>
			</div>

			<div class="row copyright">
				<div class="col-md-12 text-center">
					<p>
						<small class="block">&copy; 2017 ITOVE.com . 鄂ICP备15020545号</small> 
						<small class="block">Theme by FreeHTML5.co Images from unsplash</small>
					</p>
					<p>
						<ul class="fh5co-social-icons">
							<li><a href="https://github.com/Dotcra" target="_blank"><i class="icon-github"></i></a></li>
							<li><a href="#"><i class="icon-twitter"></i></a></li>
							<li><a href="#"><i class="icon-facebook"></i></a></li>
							<li><a href="#"><i class="icon-linkedin"></i></a></li>
							<li><a href="#"><i class="icon-dribbble"></i></a></li>
							<li><a href="#"><i class="icon-sina-weibo"></i></a></li>
							<li><a href="#"><i class="icon-qq"></i></a></li>
						</ul>
					</p>
				</div>
			</div>

		</div>
	</footer>
	</div>

	<div class="gototop js-top">
		<a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
	</div>
	
	<!-- jQuery -->
	<script src="js/jquery.min.js"></script>
	<!-- jQuery Easing -->
	<script src="js/jquery.easing.1.3.js"></script>
	<!-- Bootstrap -->
	<script src="js/bootstrap.min.js"></script>
	<!-- Waypoints -->
	<script src="js/jquery.waypoints.min.js"></script>
	<!-- Stellar Parallax -->
	<script src="js/jquery.stellar.min.js"></script>
	<!-- Carousel -->
	<script src="js/owl.carousel.min.js"></script>
	<!-- countTo -->
	<script src="js/jquery.countTo.js"></script>
	<!-- Magnific Popup -->
	<script src="js/jquery.magnific-popup.min.js"></script>
	<script src="js/magnific-popup-options.js"></script>
	<!-- Main -->
	<script src="js/main.js"></script>

	</body>
</html>


<!--
	vim:ft=html
-->
