<!DOCTYPE HTML>
<html>
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>ITOVE - IT resolve</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta name="description" content="ITOVE, 中小企业IT解决方案" />
	<meta name="keywords" content="ITOVE, 小孚, IT, 互联网, 解决方案, linux, 服务器" />
	<meta name="author" content="freehtml5.co" />

  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,700,800" rel="stylesheet">
	
	<!-- Animate.css -->
	<link rel="stylesheet" href="css/animate.css">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="css/icomoon.css">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="css/bootstrap.css">

	<!-- Magnific Popup -->
	<link rel="stylesheet" href="css/magnific-popup.css">

	<!-- Owl Carousel  -->
	<link rel="stylesheet" href="css/owl.carousel.min.css">
	<link rel="stylesheet" href="css/owl.theme.default.min.css">

	<!-- Theme style  -->
	<link rel="stylesheet" href="css/style.css">

	<!-- Modernizr JS -->
	<script src="js/modernizr-2.6.2.min.js"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="js/respond.min.js"></script>
	<![endif]-->

	</head>
	<body>
		
	<div class="fh5co-loader"></div>
	
	<div id="page">
	<nav class="fh5co-nav" role="navigation">
		<div class="top">
			<div class="container">
				<div class="row">
					<div class="col-xs-12 text-right">
						<p class="num">Call: +86 0719 8025335</p>
						<ul class="fh5co-social">
							<li><a href="#"><i class="icon-facebook"></i></a></li>
							<li><a href="#"><i class="icon-twitter"></i></a></li>
							<li><a href="#"><i class="icon-qq"></i></a></li>
							<li><a href="#"><i class="icon-sina-weibo"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div class="top-menu">
			<div class="container">
				<div class="row">
					<div class="col-xs-1">
						<div id="fh5co-logo"><a href=".">ITOVE<span>.</span></a></div>
					</div>
					<div class="col-xs-11 text-right menu-1">
						<ul>
							<li  class="<?php if($t == "") echo "active"; ?>"><a href=".">首 页</a></li>
							<li class="<?php if($t == "product") echo "active"; ?>"><a href="product">产 品</a></li>
							<li class="has-dropdown <?php if($t == "faq") echo "active"; ?>">
								<a href="faq">资 源</a>
								<ul class="dropdown">
									<li class="<?php if($t == "faq") echo "active"; ?>"><a href="faq">FAQ</a></li>
									<li><a href="http://blog.itove.com" target="_blank">Blog</a></li>
									<li><a href="api">API</a></li>
								</ul>
							</li>
							<li class="<?php if($t == "contact") echo "active"; ?>"><a href="contact">联 系</a></li>
							<li class="btn-cta"><a href="si"><span>登 录</span></a></li>
							<li class="btn-cta"><a href="#"><span>注 册</span></a></li>
						</ul>
					</div>
				</div>
				
			</div>
		</div>
	</nav>


<!--
	vim:ft=html
-->
