<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title></title>
<link rel="stylesheet" type="text/css" href="">
</head>
<body>
	<form action="" method="POST">
		<input type="text" name="username" placeholder="username">
		<input type="password" name="pass" placeholder="password">
		<input type="password" name="cpass" placeholder="confirm password">
		<input type="submit" name="signup" value="sign up">
	</form>
</body>
</html>


<!--
	vim:ft=html
-->
